services:

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama
      - redis
      - postgres

  frontend:
   build: .
   container_name: career_frontend
   working_dir: /app
   volumes:
    - .:/app
   command: >
    sh -c "
    streamlit run ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    "
   ports:
    - "8501:8501"
   depends_on:
    - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: career_user
      POSTGRES_PASSWORD: career_pass
      POSTGRES_DB: career_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  postgres_data: